# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "90f1e85483fd7c998700f6bafb4f8dc2"
application_url = "https://obj-rate-boutique-large.trycloudflare.com"
embedded = true
name = "infinite-bundler"
handle = "infinite-bundler"

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://obj-rate-boutique-large.trycloudflare.com/auth/callback",
  "https://obj-rate-boutique-large.trycloudflare.com/auth/shopify/callback",
  "https://obj-rate-boutique-large.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false

[build]
dev_store_url = "infinite-bundler.myshopify.com"
automatically_update_urls_on_dev = true
